"""empty message

Revision ID: 09da11ea88a9
Revises: dc3eaf155db5
Create Date: 2025-11-19 13:48:19.604152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09da11ea88a9'
down_revision = 'dc3eaf155db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###
