"""empty message

Revision ID: 130d9e348a33
Revises: de8f57e8184d
Create Date: 2025-11-19 13:22:07.219785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130d9e348a33'
down_revision = 'de8f57e8184d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diametro', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('periodo_rotacional', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('periodo_orbital', sa.String(length=50), nullable=True))
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.drop_column('periodo_orbital')
        batch_op.drop_column('periodo_rotacional')
        batch_op.drop_column('diametro')

    # ### end Alembic commands ###
