"""empty message

Revision ID: dc3eaf155db5
Revises: 130d9e348a33
Create Date: 2025-11-19 13:42:00.611153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3eaf155db5'
down_revision = '130d9e348a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=1250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=1250),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###
